[package]
name = "azusa-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
device_query = "=3.0.0"
image = { version = "=0.25.10", default-features = false, features = ["png"] }
xcap = { version = "=0.9.8", features = ["wgc"] }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "=0.13.13", default-features = false, features = [
    "file_chooser",
    "screenshot",
    "tokio",
] }
tokio = { version = "=1.53.1", features = ["rt-multi-thread", "net", "time"] }
url = "=2.5.8"
