[package]
name = "azusa-lens-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
slint.workspace = true
notify-rust.workspace = true
sys-locale = "=0.3.2"
arboard = { version = "=3.6.1", features = ["wayland-data-control"] }
azusa-core = { path = "../../crates/core" }
azusa-capture = { path = "../../crates/capture" }
azusa-hotkey = { path = "../../crates/hotkey" }
azusa-ocr = { path = "../../crates/ocr" }
azusa-annotation = { path = "../../crates/annotation" }
azusa-config = { path = "../../crates/config" }

[build-dependencies]
slint-build.workspace = true
